import type { SoundEffectDefinition } from "./soundEffects";

const kenney = "Kenney / kenney.nl";
const openGameArt = "OpenGameArt";
const kenneyPage = (slug: string) => `https://kenney.nl/assets/${slug}`;
const ogaPage = (slug: string) => `https://opengameart.org/content/${slug}`;
const sound = (
  id: string, name: string, icon: string, description: string,
  category: SoundEffectDefinition["category"], source: string, credit: string, sourcePage: string
): SoundEffectDefinition => ({ id, name, icon, description, category, source, license: "CC0", credit, sourcePage });

export const DIVERSE_SOUND_EFFECTS: readonly SoundEffectDefinition[] = [
  sound("kenney-card-fan", "카드 펼치기", "🃏", "카드를 부채처럼 펼치는 소리", "school", "/sound-effects/curated/kenney/card-fan-1.ogg", kenney, kenneyPage("casino-audio")),
  sound("kenney-card-place", "카드 내려놓기", "🃏", "책상에 카드를 한 장 놓는 소리", "school", "/sound-effects/curated/kenney/card-place-1.ogg", kenney, kenneyPage("casino-audio")),
  sound("kenney-card-shuffle", "카드 섞기", "🃏", "여러 장의 카드를 섞는 소리", "school", "/sound-effects/curated/kenney/card-shuffle.ogg", kenney, kenneyPage("casino-audio")),
  sound("kenney-card-pack-open", "카드 상자 열기", "📦", "작은 카드 상자를 여는 소리", "school", "/sound-effects/curated/kenney/cards-pack-open-1.ogg", kenney, kenneyPage("casino-audio")),
  sound("kenney-chip-lay", "놀이 칩 놓기", "🔴", "놀이판에 칩 하나를 놓는 소리", "school", "/sound-effects/curated/kenney/chip-lay-1.ogg", kenney, kenneyPage("casino-audio")),
  sound("kenney-chips-collide", "놀이 칩 부딪힘", "🟡", "여러 놀이 칩이 서로 부딪히는 소리", "school", "/sound-effects/curated/kenney/chips-collide-1.ogg", kenney, kenneyPage("casino-audio")),
  sound("kenney-dice-shake", "주사위 흔들기", "🎲", "손 안에서 주사위를 흔드는 소리", "school", "/sound-effects/curated/kenney/dice-shake-1.ogg", kenney, kenneyPage("casino-audio")),
  sound("kenney-dice-throw", "주사위 굴리기", "🎲", "주사위가 바닥을 구르는 소리", "school", "/sound-effects/curated/kenney/dice-throw-1.ogg", kenney, kenneyPage("casino-audio")),
  sound("kenney-belt-handle", "가방 끈 만지기", "🎒", "가방이나 허리띠의 끈을 움직이는 소리", "school", "/sound-effects/curated/kenney/beltHandle1.ogg", kenney, kenneyPage("rpg-audio")),
  sound("kenney-book-close", "책 덮기", "📕", "읽던 책을 덮는 소리", "school", "/sound-effects/curated/kenney/bookClose.ogg", kenney, kenneyPage("rpg-audio")),
  sound("kenney-book-flip", "책장 빠르게 넘기기", "📖", "책장을 빠르게 넘기는 소리", "school", "/sound-effects/curated/kenney/bookFlip1.ogg", kenney, kenneyPage("rpg-audio")),
  sound("kenney-book-open", "책 펼치기", "📖", "닫힌 책을 펼치는 소리", "school", "/sound-effects/curated/kenney/bookOpen.ogg", kenney, kenneyPage("rpg-audio")),
  sound("kenney-book-place", "책 내려놓기", "📚", "책상 위에 책을 내려놓는 소리", "school", "/sound-effects/curated/kenney/bookPlace1.ogg", kenney, kenneyPage("rpg-audio")),
  sound("kenney-chop", "도마 위 썰기", "🥕", "도마 위에서 재료를 한 번 써는 소리", "home", "/sound-effects/curated/kenney/chop.ogg", kenney, kenneyPage("rpg-audio")),
  sound("kenney-cloth", "옷감 스치기", "🧣", "천이나 옷이 부드럽게 스치는 소리", "body", "/sound-effects/curated/kenney/cloth1.ogg", kenney, kenneyPage("rpg-audio")),
  sound("kenney-creak", "나무 삐걱임", "🪵", "오래된 나무가 천천히 삐걱이는 소리", "home", "/sound-effects/curated/kenney/creak1.ogg", kenney, kenneyPage("rpg-audio")),
  sound("kenney-metal-slide", "금속 도구 꺼내기", "🛠️", "금속 도구가 케이스에서 미끄러지는 소리", "home", "/sound-effects/curated/kenney/drawKnife1.ogg", kenney, kenneyPage("rpg-audio")),
  sound("kenney-leather-drop", "가죽 주머니 떨어짐", "👝", "작은 가죽 주머니가 바닥에 떨어지는 소리", "home", "/sound-effects/curated/kenney/dropLeather.ogg", kenney, kenneyPage("rpg-audio")),
  sound("kenney-coins", "동전 한 움큼", "🪙", "여러 동전을 손으로 움직이는 소리", "home", "/sound-effects/curated/kenney/handleCoins.ogg", kenney, kenneyPage("rpg-audio")),
  sound("kenney-metal-latch", "금속 걸쇠", "🔒", "작은 금속 걸쇠를 잠그는 소리", "home", "/sound-effects/curated/kenney/metalLatch.ogg", kenney, kenneyPage("rpg-audio")),
  sound("kenney-magic-fall", "마법이 내려오는 소리", "🪄", "높은 음이 아래로 미끄러지는 마법 소리", "magic", "/sound-effects/curated/kenney/highDown.ogg", kenney, kenneyPage("digital-audio")),
  sound("kenney-magic-rise", "마법이 올라가는 소리", "✨", "높은 음이 위로 솟아오르는 마법 소리", "magic", "/sound-effects/curated/kenney/highUp.ogg", kenney, kenneyPage("digital-audio")),
  sound("kenney-low-signal", "낮은 우주 신호", "📡", "낮고 짧게 울리는 우주 신호", "magic", "/sound-effects/curated/kenney/lowRandom.ogg", kenney, kenneyPage("digital-audio")),
  sound("kenney-three-low-tones", "낮은 신호 세 번", "🔵", "낮은 전자음이 세 번 이어지는 소리", "magic", "/sound-effects/curated/kenney/lowThreeTone.ogg", kenney, kenneyPage("digital-audio")),
  sound("kenney-happy-signal", "기쁜 알림", "🌟", "성공한 순간에 어울리는 밝은 전자음", "magic", "/sound-effects/curated/kenney/pepSound1.ogg", kenney, kenneyPage("digital-audio")),
  sound("kenney-phase-jump", "순간 이동", "🌀", "다른 곳으로 순간 이동하는 듯한 소리", "magic", "/sound-effects/curated/kenney/phaseJump1.ogg", kenney, kenneyPage("digital-audio")),
  sound("kenney-phaser-down", "우주선 하강", "🛸", "우주선이 아래로 내려가는 전자음", "vehicle", "/sound-effects/curated/kenney/phaserDown1.ogg", kenney, kenneyPage("digital-audio")),
  sound("kenney-phaser-up", "우주선 상승", "🚀", "우주선이 위로 올라가는 전자음", "vehicle", "/sound-effects/curated/kenney/phaserUp1.ogg", kenney, kenneyPage("digital-audio")),
  sound("kenney-power-up", "힘이 차오르기", "⚡", "새로운 힘이 차오르는 듯한 소리", "magic", "/sound-effects/curated/kenney/powerUp1.ogg", kenney, kenneyPage("digital-audio")),
  sound("kenney-space-trash", "우주 잔해 부딪힘", "🛰️", "우주 공간의 작은 물체가 부딪히는 소리", "vehicle", "/sound-effects/curated/kenney/spaceTrash1.ogg", kenney, kenneyPage("digital-audio")),
  sound("kenney-three-tones", "전자 신호 세 번", "📟", "서로 다른 전자음이 세 번 울리는 소리", "magic", "/sound-effects/curated/kenney/threeTone1.ogg", kenney, kenneyPage("digital-audio")),
  sound("kenney-zap-rise", "번쩍 솟는 빛", "⚡", "빛줄기가 위로 빠르게 솟는 소리", "magic", "/sound-effects/curated/kenney/zapThreeToneUp.ogg", kenney, kenneyPage("digital-audio")),
  sound("kenney-computer-room", "우주 컴퓨터", "🖥️", "우주선 컴퓨터가 계속 작동하는 소리", "vehicle", "/sound-effects/curated/kenney/computerNoise_000.ogg", kenney, kenneyPage("sci-fi-sounds")),
  sound("kenney-space-door", "우주선 문 열기", "🚪", "미래의 자동문이 열리는 소리", "vehicle", "/sound-effects/curated/kenney/doorOpen_000.ogg", kenney, kenneyPage("sci-fi-sounds")),
  sound("kenney-circular-engine", "둥글게 도는 엔진", "⚙️", "기계 엔진이 둥글게 회전하는 소리", "vehicle", "/sound-effects/curated/kenney/engineCircular_000.ogg", kenney, kenneyPage("sci-fi-sounds")),
  sound("kenney-space-explosion", "우주 폭발", "💥", "우주 장면에 어울리는 묵직한 폭발음", "magic", "/sound-effects/curated/kenney/explosionCrunch_000.ogg", kenney, kenneyPage("sci-fi-sounds")),
  sound("kenney-force-field", "보호막 켜기", "🛡️", "반짝이는 보호막이 생기는 소리", "magic", "/sound-effects/curated/kenney/forceField_000.ogg", kenney, kenneyPage("sci-fi-sounds")),
  sound("kenney-large-laser", "큰 빛줄기", "🔦", "굵은 빛줄기가 뻗어 나가는 소리", "magic", "/sound-effects/curated/kenney/laserLarge_000.ogg", kenney, kenneyPage("sci-fi-sounds")),
  sound("kenney-retro-laser", "옛날 우주 빛", "👾", "옛날 우주 게임 같은 짧은 빛 소리", "magic", "/sound-effects/curated/kenney/laserRetro_000.ogg", kenney, kenneyPage("sci-fi-sounds")),
  sound("kenney-slime", "말랑한 슬라임", "🟢", "말랑한 젤리가 움직이는 듯한 소리", "animal", "/sound-effects/curated/kenney/slime_000.ogg", kenney, kenneyPage("sci-fi-sounds")),
  sound("kenney-space-engine", "우주선 엔진", "🚀", "우주선이 날아갈 때 나는 엔진 소리", "vehicle", "/sound-effects/curated/kenney/spaceEngine_000.ogg", kenney, kenneyPage("sci-fi-sounds")),
  sound("kenney-thruster", "로켓 불꽃", "🔥", "로켓 아래에서 불꽃이 세게 뿜어지는 소리", "vehicle", "/sound-effects/curated/kenney/thrusterFire_000.ogg", kenney, kenneyPage("sci-fi-sounds")),
  sound("kenney-bong", "맑은 한 음", "🔔", "물방울처럼 맑게 울리는 한 음", "magic", "/sound-effects/curated/kenney/bong_001.ogg", kenney, kenneyPage("interface-sounds")),
  sound("kenney-confirmation", "정답 알림", "✅", "정답을 맞힌 순간에 어울리는 소리", "school", "/sound-effects/curated/kenney/confirmation_001.ogg", kenney, kenneyPage("interface-sounds")),
  sound("kenney-error", "다시 생각해 보기", "❗", "한 번 더 생각해 보라는 짧은 알림", "school", "/sound-effects/curated/kenney/error_001.ogg", kenney, kenneyPage("interface-sounds")),
  sound("kenney-glitch", "화면이 흔들림", "📺", "화면 신호가 잠깐 흔들리는 전자음", "magic", "/sound-effects/curated/kenney/glitch_001.ogg", kenney, kenneyPage("interface-sounds")),
  sound("kenney-grow", "커지는 마법", "🔍", "작은 것이 커지는 듯한 소리", "magic", "/sound-effects/curated/kenney/maximize_001.ogg", kenney, kenneyPage("interface-sounds")),
  sound("kenney-shrink", "작아지는 마법", "🔎", "큰 것이 작아지는 듯한 소리", "magic", "/sound-effects/curated/kenney/minimize_001.ogg", kenney, kenneyPage("interface-sounds")),
  sound("kenney-pluck", "줄 튕기기", "🎸", "짧게 줄 하나를 튕기는 소리", "percussion", "/sound-effects/curated/kenney/pluck_001.ogg", kenney, kenneyPage("interface-sounds")),
  sound("kenney-question", "궁금한 순간", "❓", "고개를 갸웃하는 장면에 어울리는 소리", "magic", "/sound-effects/curated/kenney/question_001.ogg", kenney, kenneyPage("interface-sounds")),
  sound("kenney-scratch", "긁적긁적", "✏️", "연필이나 작은 물체로 긁는 듯한 소리", "school", "/sound-effects/curated/kenney/scratch_001.ogg", kenney, kenneyPage("interface-sounds")),
  sound("kenney-scroll", "빠르게 훑어보기", "📜", "긴 목록이나 종이를 빠르게 훑는 듯한 소리", "school", "/sound-effects/curated/kenney/scroll_001.ogg", kenney, kenneyPage("interface-sounds")),
  sound("kenney-carpet-step", "카펫 발걸음", "👣", "푹신한 카펫 위를 걷는 소리", "body", "/sound-effects/curated/kenney/footstep_carpet_000.ogg", kenney, kenneyPage("impact-sounds")),
  sound("kenney-concrete-step", "바닥 발걸음", "👟", "단단한 바닥 위를 걷는 소리", "body", "/sound-effects/curated/kenney/footstep_concrete_000.ogg", kenney, kenneyPage("impact-sounds")),
  sound("kenney-grass-step", "풀밭 발걸음", "🌿", "풀밭 위를 사각사각 걷는 소리", "nature", "/sound-effects/curated/kenney/footstep_grass_000.ogg", kenney, kenneyPage("impact-sounds")),
  sound("kenney-snow-step", "눈밭 발걸음", "❄️", "눈을 밟으며 걷는 소리", "weather", "/sound-effects/curated/kenney/footstep_snow_000.ogg", kenney, kenneyPage("impact-sounds")),
  sound("kenney-cushion-drop", "쿠션 떨어짐", "🛋️", "부드러운 물건이 바닥에 툭 떨어지는 소리", "home", "/sound-effects/curated/kenney/impactSoft_heavy_000.ogg", kenney, kenneyPage("impact-sounds")),
  sound("oga-alien", "외계 생물", "👽", "낯선 외계 생물이 내는 소리", "animal", "/sound-effects/curated/opengameart/alien_01.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-dog-bark", "강아지 짖기", "🐶", "강아지가 짧게 멍멍 짖는 소리", "animal", "/sound-effects/curated/opengameart/barking_01.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-breath", "숨 고르기", "😮‍💨", "달린 뒤 숨을 고르는 듯한 소리", "body", "/sound-effects/curated/opengameart/breath.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-bug", "큰 벌레", "🐛", "상상 속 큰 벌레가 움직이는 소리", "animal", "/sound-effects/curated/opengameart/bug_01.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-burble", "물속 생물", "🐠", "물속 생물이 보글거리는 듯한 소리", "animal", "/sound-effects/curated/opengameart/burble_01.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-burp", "트림", "😳", "익살스럽게 짧게 나는 트림 소리", "body", "/sound-effects/curated/opengameart/burp_01.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-cough", "기침", "😷", "가볍게 콜록하는 소리", "body", "/sound-effects/curated/opengameart/cough_01.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-cute-creature", "작고 귀여운 생물", "🐣", "작은 상상 동물이 내는 귀여운 소리", "animal", "/sound-effects/curated/opengameart/cute_01.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-eating", "냠냠 먹기", "🍎", "상상 동물이 음식을 먹는 소리", "animal", "/sound-effects/curated/opengameart/eat_01.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-howl", "늑대 울음", "🐺", "멀리서 들리는 늑대의 울음소리", "animal", "/sound-effects/curated/opengameart/howl.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-monster", "동굴 괴물", "👹", "동굴 속 상상 괴물이 내는 소리", "animal", "/sound-effects/curated/opengameart/monster_01.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-roar", "큰 동물 포효", "🦁", "큰 동물이 힘차게 포효하는 소리", "animal", "/sound-effects/curated/opengameart/roar_01.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-snore", "코골이", "😴", "깊이 잠든 동물이 코를 고는 소리", "animal", "/sound-effects/curated/opengameart/snore.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-troll", "숲속 트롤", "🌲", "숲속 상상 생물 트롤의 목소리", "animal", "/sound-effects/curated/opengameart/troll_01.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-ooh", "감탄하기", "😮", "신기한 것을 보고 감탄하는 목소리", "body", "/sound-effects/curated/opengameart/ooh.ogg", "rubberduck / OpenGameArt", ogaPage("80-cc0-creature-sfx")),
  sound("oga-lighter-click", "작은 점화기 딸깍", "🔥", "작은 점화기를 누를 때 나는 딸깍 소리", "home", "/sound-effects/curated/opengameart/Cigarette_Lighter_01.wav", "TokyoGeisha / OpenGameArt", ogaPage("58-random-sound-effects")),
  sound("oga-coins-drop", "동전 떨어짐", "🪙", "동전 여러 개가 바닥에 떨어지는 소리", "home", "/sound-effects/curated/opengameart/Coins_01.wav", "TokyoGeisha / OpenGameArt", ogaPage("58-random-sound-effects")),
  sound("oga-crunch", "바삭 깨물기", "🍪", "바삭한 과자를 한입 깨무는 소리", "body", "/sound-effects/curated/opengameart/Crunch_01.wav", "TokyoGeisha / OpenGameArt", ogaPage("58-random-sound-effects")),
  sound("oga-finger-click", "손가락 튕기기", "🫰", "손가락을 딱 튕기는 소리", "body", "/sound-effects/curated/opengameart/Finger_Click_01.wav", "TokyoGeisha / OpenGameArt", ogaPage("58-random-sound-effects")),
  sound("oga-fizz", "탄산 거품", "🥤", "탄산음료 거품이 치익 올라오는 소리", "home", "/sound-effects/curated/opengameart/Fizz_01.wav", "TokyoGeisha / OpenGameArt", ogaPage("58-random-sound-effects")),
  sound("oga-hand-clap", "손뼉 한 번", "👏", "두 손을 마주쳐 박수치는 소리", "body", "/sound-effects/curated/opengameart/Hand_Clap_01.wav", "TokyoGeisha / OpenGameArt", ogaPage("58-random-sound-effects")),
  sound("oga-keys-jingle", "열쇠 꾸러미", "🔑", "여러 열쇠가 짤랑거리는 소리", "home", "/sound-effects/curated/opengameart/Keys_01.wav", "TokyoGeisha / OpenGameArt", ogaPage("58-random-sound-effects")),
  sound("oga-scissors", "가위질", "✂️", "종이를 가위로 싹둑 자르는 소리", "school", "/sound-effects/curated/opengameart/Scissors_Snip_01.wav", "TokyoGeisha / OpenGameArt", ogaPage("58-random-sound-effects")),
  sound("oga-chain", "작은 사슬 흔들기", "⛓️", "작은 금속 사슬이 흔들리는 소리", "home", "/sound-effects/curated/opengameart/Small_Chain_Rattle_01.wav", "TokyoGeisha / OpenGameArt", ogaPage("58-random-sound-effects")),
  sound("oga-spoon-cup", "컵에 숟가락", "🥄", "숟가락이 컵에 맑게 부딪히는 소리", "home", "/sound-effects/curated/opengameart/Spoon_On_Cup_01.wav", "TokyoGeisha / OpenGameArt", ogaPage("58-random-sound-effects")),
  sound("oga-drawer-open", "서랍 열기", "🗄️", "나무 서랍을 여는 소리", "home", "/sound-effects/curated/opengameart/drawer_open.wav", "laleksic / OpenGameArt", ogaPage("various-sound-effects")),
  sound("oga-drawer-close", "서랍 닫기", "🗄️", "나무 서랍을 닫는 소리", "home", "/sound-effects/curated/opengameart/drawer_close.wav", "laleksic / OpenGameArt", ogaPage("various-sound-effects")),
  sound("oga-floor-creak", "마룻바닥 삐걱임", "🏚️", "오래된 마룻바닥이 삐걱이는 소리", "home", "/sound-effects/curated/opengameart/floor_creak1.wav", "laleksic / OpenGameArt", ogaPage("various-sound-effects")),
  sound("oga-lock", "자물쇠 잠그기", "🔒", "자물쇠가 달칵 잠기는 소리", "home", "/sound-effects/curated/opengameart/lock.wav", "laleksic / OpenGameArt", ogaPage("various-sound-effects")),
  sound("oga-lock-pick", "자물쇠 살펴보기", "🔐", "작은 자물쇠 안쪽이 달칵거리는 소리", "home", "/sound-effects/curated/opengameart/lock_pick.wav", "laleksic / OpenGameArt", ogaPage("various-sound-effects")),
  sound("oga-manhole", "무거운 뚜껑 열기", "🕳️", "무거운 금속 뚜껑을 여는 소리", "city", "/sound-effects/curated/opengameart/manhole_open.wav", "laleksic / OpenGameArt", ogaPage("various-sound-effects")),
  sound("oga-match", "성냥 켜기", "🔥", "성냥을 그어 불을 붙이는 소리", "home", "/sound-effects/curated/opengameart/match.wav", "laleksic / OpenGameArt", ogaPage("various-sound-effects")),
  sound("oga-water-tap", "수도꼭지 물", "🚰", "수도꼭지에서 물이 나오는 소리", "home", "/sound-effects/curated/opengameart/tap_water.wav", "laleksic / OpenGameArt", ogaPage("various-sound-effects")),
  sound("oga-turn-page", "책장 넘기기", "📄", "책장을 한 장 천천히 넘기는 소리", "school", "/sound-effects/curated/opengameart/turn_page.wav", "laleksic / OpenGameArt", ogaPage("various-sound-effects"))
];
